/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BatatinhaRussa2021 (https://sketchfab.com/BatatinhaRussa2021)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/white-and-black-voxel-cat-d25ff8a86e7b497cbc38bc945bdd693b
title: White and Black Voxel Cat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cat.gltf')
  const size = 0.9
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2.2, 0.1, 0.35]} position={[0,-1.7,0]} scale={[size,size,size]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.palette} />
      </group>
    </group>
  )
}

useGLTF.preload('/cat.gltf')
